Add variable setting for tag based on event type

diff --git a/.github/workflows/validate-semver.yaml b/.github/workflows/validate-semver.yaml
--- a/.github/workflows/validate-semver.yaml
+++ b/.github/workflows/validate-semver.yaml
@@ -17,11 +17,27 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # タグの値の参照方法がイベントごとに異なるため、後続処理で参照方法を統一できるように変数を用意する
+      - name: Set Variables Based on Event
+        id: set-vars
+        run: |
+          tag=""
+          if [ "${{ github.event_name }}" == "push" ]; then
+            tag=${GITHUB_REF#refs/tags/}
+          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+            tag=${{ inputs.version }}
+          else
+            echo "Error: Unsupported event_name '${{ github.event_name }}'" >&2
+            exit 1
+          fi
+          echo "tag=${tag}" >> $GITHUB_OUTPUT
+          echo "tag=${tag}"
+    
       # タグの文字列をチェックする
       - name: Validate Semantic Version
         id: validate-version
         run: |
-          VERSION=${{ github.event.inputs.version }}
+          VERSION=${{ steps.set-vars.outputs.tag }}
           SEMVER_REGEX="^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
           if [[ ! "$VERSION" =~ $SEMVER_REGEX ]]; then
             echo "Invalid version: ${VERSION}"
